name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build -t nieves/prestador-angular:${{ github.sha }} .
    - name: Pull the Docker image to Docker Hub
      run: docker push nieves/prestador-angular:${{ github.sha }}
